name: co_op
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  awesome_dialog: ^3.0.2
  cached_network_image: null
  calendar_timeline: ^1.0.5
  carousel_slider: ^4.1.1
  circular_countdown_timer: ^0.2.2
  cloud_firestore: ^4.0.2
  connectivity_plus: null
  cupertino_icons: ^1.0.2
  custom_marker: ^1.0.0
  date_picker_timeline: ^1.2.3
  dotted_border: ^2.0.0+3
  email_validator: ^2.1.17
  file_picker: ^5.2.2
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_datetime_picker: ^1.5.1
  flutter_event_calendar: null
  flutter_launcher_icons: ^0.10.0
  flutter_local_notifications: ^9.8.0+1
  flutter_native_splash: null
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.1.1
  get: null
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  google_maps_place_picker_mb: ^2.0.0-mb.22
  hexcolor: null
  horizontal_calendar: ^1.0.1
  intl: null
  introduction_screen: ^3.0.2
  jiffy: ^5.0.0
  location: ^4.4.0
  lottie: null
  numberpicker: ^2.1.1
  pin_code_fields: ^7.4.0
  provider: null
  pull_to_refresh: ^2.0.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  sliver_header_delegate: ^0.0.1
  smooth_page_indicator: ^1.0.0+2
  social_login_buttons: ^1.0.6+2
  syncfusion_flutter_datepicker: ^20.3.58
  vibration: ^1.7.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
